### ISSUE TITLE
Wrong place and IN/OUT connexions

### ISSUE THREAD

**Issue by JeromeSi** [thomas-senechal/massadoption-issues#1]
Hi
Very good job !
My node is near Bordeaux (France, Gironde) and not in Paris
I don't have 4 IN and 4 OUT but 10 and 10 in get_status.
N1mAgpXKfrLgZoJrifHRmTNiJfncdZLqScG6X2ZyexNGLtF7r7W
I'm using only IPv6.
I don't know if it's can help you.

**Comment by thomas-senechal** [comment]
Hi ! 

Thanks a lot !

> My node is near Bordeaux (France, Gironde) and not in Paris

I get Node position using https://ip-api.com/ . AFAIK, the position is more or less wrong depending on multiple factors such as, if your interner provider updated the IP address position correctly or not
So it's okay if your node is not at the right place, might be fixed at some point !

> I don't have 4 IN and 4 OUT but 10 and 10 in get_status.

I checked in the DB, and it looks like your node public API (`33035`: https://docs.massa.net/docs/build/api/jsonrpc) port is not open. When the port is not open, I can't get some informations such as the IN/OUT connections, so I check in the other nodes to see if the requested node is somewhere. 

Note that if you opened the port recently, it takes approximately 1 hour for the map to show the update.

**Comment by JeromeSi** [comment]
My port 33035 is closed.
I don't know why. I'm searching.
